# Slicing and Indexing

NumPy provides powerful ways to access and modify array elements using indexing (selecting individual elements) and slicing (selecting subarrays). These operations are similar to Python lists but with additional features for multi-dimensional arrays.

## Indexing

### 1D Array Indexing

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access the 2nd element (0-based index)
print(arr[1])  # Output: 20

# Modify the 3rd element
arr[2] = 99
print(arr)  # Output: [10 20 99 40 50]

20
[10 20 99 40 50]


### 2D Array (Matrix) Indexing

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get element at row 1, column 2
print(arr[1, 2])  # Output: 6

# Modify element at row 0, column 1
arr[0, 1] = 99
print(arr)
# Output:
# [[ 1 99  3]
#  [ 4  5  6]]

6
[[ 1 99  3]
 [ 4  5  6]]


### Negative Indexing

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access the last element
print(arr[-1])  # Output: 50

# Access the second-last element
print(arr[-2])  # Output: 40

50
40


## Slicing

Slicing extracts a portion of an array in the form start:stop:step

### 1D Array Slicing

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Get elements from index 1 to 3 (exclusive)
print(arr[1:3])  # Output: [20 30]

# Get every alternate element
print(arr[::2])  # Output: [10 30 50]

# Reverse the array
print(arr[::-1])  # Output: [50 40 30 20 10]

[20 30]
[10 30 50]
[50 40 30 20 10]


### 2D Array Slicing

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the first row
print(arr[0, :])  # Output: [1 2 3]

# Get the second column
print(arr[:, 1])  # Output: [2 5 8]

# Get a submatrix (rows 0-1, columns 1-2)
print(arr[0:2, 1:3])
# Output:
# [[2 3]
# [5 6]]

[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


### Modifying Slices

In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Change elements from index 1 to 3
arr[1:3] = [99, 100]
print(arr)  # Output: [10 99 100 40 50]

[ 10  99 100  40  50]


## Advanced Indexing

NumPy supports boolean masking and fancy indexing for more complex selections.

### Boolean Masking (Conditional Selection)

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Get elements greater than 3
mask = arr > 3
print(arr[mask])  # Output: [4 5]

# Set all even numbers to 0
arr[arr % 2 == 0] = 0
print(arr)  # Output: [1 0 3 0 5]

[4 5]
[1 0 3 0 5]


### Fancy Indexing (Using Integer Arrays)

In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Select elements at positions 0, 2, and 4
indices = [0, 2, 4]
print(arr[indices])  # Output: [10 30 50]

# Modify selected elements
arr[indices] = [100, 200, 300]
print(arr)  # Output: [100 20 200 40 300]

[10 30 50]
[100  20 200  40 300]


## Key Differences Between Indexing & Slicing

<table style="float: left;">
    <tr>
        <td>Feature</td>
        <td>Indexing (arr[i])</td>
        <td>Slicing (arr[i:j])</td>
    </tr>
    <tr>
        <td>Returns</td>
        <td>Single element</td>
        <td>Subarray (view)</td>
    </tr>
    <tr>
        <td>Modifies</td>
        <td>Original array</td>
        <td>Original array (if assigned)</td>
    </tr>
    <tr>
        <td>Memory</td>
        <td>No copy (direct reference)</td>
        <td>Creates a view (no copy)</td>
    </tr>
    <tr>
        <td>Usage</td>
        <td>arr[2]</td>
        <td>arr[1:4]</td>
    </tr>
</table>

## Important Notes
Slicing returns a view (not a copy), so modifying a slice affects the original array.

```
arr = np.array([1, 2, 3, 4])
sub_arr = arr[1:3]  # This is a view
sub_arr[0] = 99
print(arr)  # Output: [1 99 3 4] (original modified)
```

To create an independent copy, use .copy():

```
sub_arr = arr[1:3].copy()  # Now changes won't affect original
```

Ellipsis (...) is used in multi-dimensional arrays to skip dimensions:

```
arr = np.random.rand(2, 3, 4)
print(arr[..., 0])  # Equivalent to arr[:, :, 0]
```