# Modifying Arrays

## Reshaping Arrays

Reshaping arrays in NumPy refers to changing the structure (shape) of an array without changing its data. This is a fundamental operation when working with numerical data in Python. Reshaping is particularly important in data science for preparing data for machine learning models, image processing, and linear algebra operations.

### Key Concepts
- **Shape**: The dimensions of an array (e.g., (3,4) for a 2D array with 3 rows and 4 columns)
- **Size**: Total number of elements in the array (product of all dimensions)

### reshape() method

In [3]:
import numpy as np

arr = np.arange(12)  # 1D array with 12 elements
print(arr)
reshaped = arr.reshape(3, 4)  # Convert to 3x4 array
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Reshaping with -1

In [4]:
import numpy as np

arr = np.arange(24)
print(arr)
reshaped = arr.reshape(2, 3, -1)  # Results in 2x3x4 array
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## Flatten An Array

Convert multi-dimensional arrays to 1D

In [5]:
import numpy as np

arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)
flat = arr_2d.flatten()
print(flat)

[[1 2]
 [3 4]]
[1 2 3 4]


## Resizing Array

The resize() function in NumPy is used to change the size (total number of elements) of an array, unlike reshape() which only changes the shape while keeping the size constant.

### Key Features of resize()
- Can change the total number of elements (unlike reshape)
- Can either return a new array or modify the original (depending on which version you use)
- Handles size changes by repeating elements or padding with zeros when needed

### np.resize(array, new_shape)

- Returns a new array with the specified shape
- If new size is larger, the original data is repeated
- If new size is smaller, the array is truncated

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

# Larger array - elements are repeated
larger = np.resize(arr, (8,))  # Returns array([1, 2, 3, 4, 1, 2, 3, 4])
print(larger)

# Smaller array - elements are truncated
smaller = np.resize(arr, (3,))  # Returns array([1, 2, 3])
print(smaller)

[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3]


### ndarray.resize(new_shape, refcheck=True)

- Modifies the array in-place
- If new size is larger, pads with zeros (not repeating elements)
- Requires the array to be the sole owner of its memory (no views)

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)
arr.resize((6,))  # Now array([1, 2, 3, 4, 0, 0])
print(arr)

[1 2 3 4]
[1 2 3 4 0 0]


## Transpose Array

The transpose operation in NumPy is a fundamental array manipulation that rearranges the dimensions of an array, effectively flipping it over its diagonal. This operation is particularly important in linear algebra, data science, and machine learning.

### Common Use Cases
- Preparing matrices for linear algebra operations
- Reorienting image data (height ↔ width)
- Converting between row-major and column-major formats
- Reshaping data for machine learning models

### ndarray.T attribute
The simplest way to transpose a NumPy array

In [10]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.T)
# Output:
# array([[1, 4],
#        [2, 5],
#        [3, 6]])

[[1 4]
 [2 5]
 [3 6]]


### np.transpose() function
More flexible version that can handle multi-dimensional arrays

In [12]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transposed = np.transpose(arr)

print(transposed)

[[1 4]
 [2 5]
 [3 6]]


### Advanced Usage

#### Specifying axis order (for multi-dimensional arrays)

In [13]:
import numpy as np

arr_3d = np.arange(24).reshape(2, 3, 4)

# Default transpose (reverse dimensions)
print(np.transpose(arr_3d).shape)  # (4, 3, 2)

# Custom axis order
print(np.transpose(arr_3d, axes=(1, 0, 2)).shape)  # (3, 2, 4)

(4, 3, 2)
(3, 2, 4)


#### Matrix multiplication with transpose

In [15]:
import numpy as np

A = np.random.rand(3, 4)
B = np.random.rand(5, 4)

# Matrix multiplication: A (3×4) × B.T (4×5) → (3×5)
result = np.dot(A, B.T)
print(result)

[[1.16182657 1.3000808  0.88022423 0.79206718 0.8083093 ]
 [0.45753778 0.47466875 0.37325321 0.33589181 0.40693119]
 [0.86837363 0.86914081 0.4208507  0.86931373 0.74313222]]


## swapaxes
The swapaxes function in NumPy is used to interchange two axes of an array. It's a more flexible operation than transpose when you only want to swap specific dimensions of a multi-dimensional array.

### Basic Syntax
```
numpy.swapaxes(a, axis1, axis2)
```

Where:
- a: Input array
- axis1: First axis to swap
- axis2: Second axis to swap

### Key Characteristics
- Returns a view (not a copy) of the array whenever possible
- Doesn't change the data - only rearranges how it's indexed
- Works with arrays of any dimension (≥ 2)
- More targeted than transpose - only swaps specified axes

### Common Use Cases
- **Image processing**: Swapping color channels (RGB → BGR)
- **Time series data**: Swapping time and feature dimensions
- **Neural networks**: Adjusting input dimensions for different frameworks
- **Tensor operations**: Preparing tensors for specific mathematical operations

### 2D Array (Same as Transpose)

In [17]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

swapped = np.swapaxes(arr, 0, 1)
# Equivalent to arr.T
# Result:
# array([[1, 4],
#        [2, 5],
#        [3, 6]])
print(swapped)

[[1 4]
 [2 5]
 [3 6]]


### 3D Array

In [18]:
import numpy as np

arr_3d = np.arange(24).reshape(2, 3, 4)

# Swap height and depth (axes 0 and 2)
swapped = np.swapaxes(arr_3d, 0, 2)
print(swapped.shape)  # (4, 3, 2)

(4, 3, 2)


### 4D Array

In [19]:
import numpy as np

arr_4d = np.random.rand(2, 3, 4, 5)

# Swap second and third dimensions
swapped = np.swapaxes(arr_4d, 1, 2)
print(swapped.shape)  # (2, 4, 3, 5)

(2, 4, 3, 5)
