# Stacking and Splitting

In NumPy, stacking and splitting are operations used to combine and divide arrays, respectively. They are essential for data manipulation in machine learning, scientific computing, and numerical analysis

## Stacking

Stacking combines multiple arrays into a single array along a specified axis

### np.stack()

- Stacks arrays along a new axis (does not just concatenate).
- All input arrays must have the same shape.
- Syntax: `np.stack((array1, array2, ...), axis=0)`

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack along a new axis (default: axis=0)
stacked = np.stack((a, b))
print(stacked)

# If axis=1, the arrays are stacked column-wise:
stacked_col = np.stack((a, b), axis=1)
print(stacked_col)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### np.vstack() (Vertical Stack)

- Stacks arrays row-wise (vertically).
- Works even if arrays are 1D (treats them as rows).
- Syntax: `np.vstack((array1, array2, ...))`

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stacked = np.vstack((a, b))
print(v_stacked)

[[1 2 3]
 [4 5 6]]


### np.hstack() (Horizontal Stack)

- Stacks arrays column-wise (horizontally).
- Syntax: `np.hstack((array1, array2, ...))`

In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h_stacked = np.hstack((a, b))
print(h_stacked)

[1 2 3 4 5 6]


### np.dstack() (Depth Stack)

- Stacks arrays along the third axis (depth-wise).
- Useful for 3D data (e.g., RGB images).
- Syntax: `np.dstack((array1, array2, ...))`

In [6]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

d_stacked = np.dstack((a, b))
print(d_stacked)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## Splitting 

Splitting divides an array into multiple sub-arrays

### np.split()

- Splits an array into equal or custom-sized sub-arrays.
- Syntax: `np.split(array, indices_or_sections, axis=0)`
    - `indices_or_sections`: Number of equal splits or list of split points.

In [8]:
import numpy as np

arr = np.arange(9)  # [0, 1, 2, 3, 4, 5, 6, 7, 8]
split_arr = np.split(arr, 3)
print(split_arr)

split_custom = np.split(arr, [2, 5])  # Split at indices 2 and 5
print(split_custom)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]


### np.vsplit() (Vertical Split)

- Splits row-wise (along axis=0).
- Syntax: `np.vsplit(array, num_splits)`

In [13]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
v_split = np.vsplit(arr, 3)
print(v_split)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


### np.hsplit() (Horizontal Split)

- Splits column-wise (along axis=1).
- Syntax: `np.hsplit(array, num_splits)`

In [14]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
h_split = np.hsplit(arr, 3)
print(h_split)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


### np.dsplit() (Depth Split)

- Splits along the third axis (for 3D arrays).
- Syntax: `np.dsplit(array, num_splits)`

In [15]:
import numpy as np

arr = np.arange(8).reshape(2, 2, 2)  # 3D array
d_split = np.dsplit(arr, 2)
print(d_split)

[array([[[0],
        [2]],

       [[4],
        [6]]]), array([[[1],
        [3]],

       [[5],
        [7]]])]
